simulation:

  services: 

    spawn_sdf_model: 'gazebo/spawn_sdf_model'
    delete_model: 'gazebo/delete_model'
    reset_simulation: 'gazebo/reset_simulation'
    reset_world: 'gazebo/reset_world'
    set_model_state: 'gazebo/set_model_state'
    pause_physics: 'gazebo/pause_physics'
    unpause_physics: 'gazebo/unpause_physics'


  subscribers:

    model_states: 'gazebo/model_states'

turtlebot3:

  subscribers:

    odom: 'odom'
    scan: 'scan'

  publishers:

    cmd_vel: 'cmd_vel'
    debbug: 'debbug'


params:
  state_dimension: 6 
  action_dimension: 2
  learning_rate: 0.001
  gamma: 0.8
  alpha: 0.2
  buffer_size: 50000
  batch_size: 512
  num_episodes: 10000
  max_steps: 2000
  stoped_episode: 0
  max_reward: 0